<?php
/**
 * Maryanov
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@maryanov.com so we can send you a copy immediately.
 *
 * @category   Maryanov
 * @package    Maryanov_Rahunok
 * @author     Maryanov Anton
 * @copyright  Copyright (c) 2009 Maryanov Anton (http://www.maryanov.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<?php echo $this->getChildHtml('content') ?>
