#!/bin/sh

#Used variables: slavedir, masterdir, host, port, user

counter=1
while [ "$counter" -le "$#" ]
do
	var=`eval echo '$'$counter`
	varname=`echo $var | sed 's/\([^=]\+\)=\(.*\)/\1/'`
	varval=`echo $var | sed 's/\([^=]\+\)=\(.*\)/\2/'`
	eval $varname='$varval' 2>/dev/null
	counter=`expr $counter + 1`
done

if [ "x$masterdir" = "x" ]
then
	echo 'Need path to master.'
	exit 1
fi

if [ "x$slavedir" = "x" ]
then
	echo 'Need path to slave.'
	exit 1
fi


if [ "x$host" != "x" ]
then
	ssh="ssh "
	scp="scp "
	if [ "x$port" != "x" ]
	then
		ssh="${ssh}-p${port} "
		scp="${scp}-P${port} "
	fi
	if [ "x$user" != "x" ]
	then
		ssh="${ssh}${user}@"
		scp="${scp}${user}@"
	fi
	ssh="${ssh}${host}"
	scp="${scp}${host}:"
fi

masterdiresc=`echo "$masterdir" | sed 's/\//\\\\\//g'`

slavelogs=`ls -1 ${slavedir}/masterlog/`
masterlogs=`$ssh ls -1 ${masterdir}/log/bin/`
uniqlogs=`echo "${slavelogs}\n${masterlogs}" | sort | uniq -u`
logfiles=`echo "${uniqlogs}\n${masterlogs}" | sort | uniq -d`

if [ "x$logfiles" != "x" ]
then
	tocopy=`echo "${logfiles}" | sed 's/^/'${masterdiresc}'\/log\/bin\//' | tr '\n' ' ' | sed 's/\(^\s*\)\|\(\s*$\)//g'`
	if [ "x$scp" != "x" ]
	then
		${scp}"${tocopy}" ${slavedir}/masterlog/
	else
		cp ${tocopy} ${slavedir}/masterlog/
	fi
else
	echo "Nothing to do."
fi

exit 0

